Sample .travis.yml file:
language: ruby
os: osx

rvm: # the Ruby versions to be used
  - 2.3.1

addons:
  chrome: stable

before_install:
  - gem install watir-webdriver

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
